package com.fitness.fitnessCru.utility

interface Constants {
    companion object {
        const val TAG = "<<< FIT-CRU >>>"
        const val DESTINATION = "DESTINATION"
        const val ADD_MEAL = "ADD_MEAL"
        const val COACHING = "COACHING"
        const val CHECKOUT = "CHECKOUT"
        const val MY_ORDERS = "MY_ORDERS"
        const val RECIPE = "RECIPE"
        const val STUDIO_DETAILS = "STUDIO_DETAILS"
        const val WORKOUT_BY_FITNESS = "GET_WORKOUT_BY_FITNESS"
        const val WORKOUT = "WORKOUT"
        const val WORKOUT2 = "WORKOUT2"
        const val IS_LOGGED_IN = "IS_LOGGED_IN"
        const val USER_DETAIL = "USER_DETAIL"
        const val NAME = "NAME"
        const val TOKEN = "TOKEN"
        const val QBEMAIL = "QBEMAIL"
        const val QBMOBILE = "QBMOBILE"
        const val AUTHORIZATION = "Authorization"
        const val INSIGHTS = "INSIGHTS"
        const val APPOINTMENT = "APPOINTMENT"
        const val COACH_PROFILE = "COACH_PROFILE"
        const val FEEDBACK = "FEEDBACK"
        const val GO_TO_HELL = "HEALTH"
        const val SCHEDULE_APPOINTMENT = "SCHEDULE_APPOINTMENT"
        const val MAIN_COACHING = "MAIN_COACHING"
        const val HOME_TO_WORKOUT = "HOME_TO_WORKOUT"
        const val LAB_TEST = "LAB_TEST"
        const val SELECT_COACH = "SELECT_COACH"
        const val COACH_PLAN_DETAIL = "COACH_PLAN_DETAIL"
        const val NOTIFICATION_LIST = "NOTIFICATION_LIST"
        const val ACCESS_TOKEN = "accessToken"
        const val FCMTOKEN = "FCMTOKEN"
        const val STEPS = "STEPS"
        const val CALORIE = "CALORIE"
        const val SYNC_TIME = "SYNC_TIME"
    }
}