package com.fitness.fitnessCru.network

interface API {
    companion object {

        //              const val BASE_URL = "https://app.fitcru.com/fitcru/"
        const val BASE_URL = "http://65.1.160.150/fitcru/"

        //               const val IMAGE_BASE_URL = "https://app.fitcru.com/"
        const val IMAGE_BASE_URL = "http://65.1.160.150/"

        const val SIGNUP_WITH_EMAIL = "signup-with-email"
        const val MOBILE_LOGIN = "login-with-mobile"
        const val EMAIL_LOGIN = "login"
        const val SIGNUP = "register"
        const val OTP_VERIFY = "otp-verify"
        const val RESEND_OTP = "resend-otp"
        const val USER_DETAILS = "user-detail"
        const val UPDATE_PROFILE = "update-profile"
        const val FORGOT_PASSWORD = "forgot-password"
        const val CHANGE_PASSWORD = "change-password"
        const val LOGOUT = "logout"
        const val REFRESH_TOKEN = "refresh"
        const val STUDIO = "studio"
        const val DIET_TYPE = "whats-your-diet-types"//Food Pref
        const val FITNESS_LEVEL = "your-fitness-levels"//Fitness level
        const val WHAT_BRINGS_YOU = "what-bring-you-to-fitcru"
        const val HOW_ACTIVE_YOU = "get-how-active-you"//Daily activity
        const val EMAIL_VERIFY = "email-verify"
        const val CREATE_PASS = "create-password"
        const val GET_QUESTIONS_BY_USER_ID = "get_questionnair_by_user_id"
        const val UPDATE_QUESTION = "questionnaire_user_select"
        const val GENDER_DOB = "update-gender-and-dob"
        const val WORKOUT_VIBE = "workout-vibes"//your goal
        const val CONGRATULATIONS = "questionnaire_congratulations"
        const val DASHBOARD = "dashborad"
        const val PROGRAM = "programs"
        const val FOODS = "getFoodsName"
        const val MEAL_UPDATE = "addFoodByMealType" //update-meal-by-subscriber
        const val MEAL_ADD = "addFoodByMealType"    //add-meal-by-subscriber
        const val MEAL_TYPE = "getMealTypsList"
        const val MEAL_BY_ID = "getMealTypeByFoods"
        const val NUTRITION_DASHBOARD = "nutritionDashboard"
        const val CARDIO_LIST = "cardio-list"
        const val RECIPE_DETAILS = "recipie-details"
        const val TRENDING_OFFERS = "programs-by-id"
        const val SNC_PROGRAM = "get-program-by-workout-id"
        const val COUNTRY = "countries"
        const val STATE = "states"
        const val CITY = "city"
        const val ADD_ADDRESS = "add-address"
        const val UPDATE_ADDRESS = "update-address-by-user"
        const val DELETE_ADDRESS = "delete-address-by-user"
        const val GET_ADDRESS_BY_USER = "get-address-by-user"
        const val DEFAULT_ADDRESS_BY_USER = "mark-default-address-by-user"
        const val EXERCISE = "get-exercise-by-workout-id"
        const val ACTIVITY_GOALS = "activity-goals"
        const val MY_SUMMARY = "my-summary"
        const val HEALTH_QUESTIONNAIRE = "health-questionnaire"
        const val SUBSCRIPTION = "get-feestructure-by-coach-category-and-slab-type"
        const val COACH_CATEGORY = "coach-category-types"
        const val COACH_SLAB = "coach-slab-types"
        const val GET_REMINDER = "get-reminder-by-user-id"
        const val GET_REMINDER_BY_ID = "get-reminder-by-id"
        const val UPDATE_REMINDER = "update-reminder"
        const val DELETE_REMINDER = "delete-reminder-by-id"
        const val ADD_REMINDER = "add-reminder"
        const val GET_QUESTIONNAIRE = "get-health-questionnaire"
        const val UPDATE_QUESTIONNAIRE = "health-questionnaire"
        const val IMAGE_HEALTH_QUESTIONNAIRE = "image-health-questionnaire"
        const val GET_COACH_DETAILS = "get-coach-details"
        const val COACH_SPECIALIZATION = "get-specializations"
        const val COACH_WITH_SPECIALIZATION = "get-caches-by-specialization-id"
        const val COACH_WITHOUT_SPECIALIZATION = "get-caches-by-coach-category-and-slab-type"
        const val USER_SELECT_PLAN = "user-select-plan"
        const val PLAN_DETAIL = "plan-details"
        const val CHOOSE_MONTHLY_PRICE = "choose_monthly-price-by-user"
        const val GET_HABITS = "habits"
        const val SOCIAL_MEDIA = "social-media-login"
        const val AVAILABLE_TIME_SLOT = "coach_timeslot"
        const val BOOK_APPOINTMENT = "user_book_appointment"
        const val USER_CONSUMED_MEAL = "user-consumed-meal"
        const val USER_NOT_CONSUMED_MEAL = "user-not-consumed-meal"
        const val CONSUMED_ALL = "add-all-consumed-meal"
        const val REMOVE_ALL_CONSUME = "remove-all-consumed-meal"
        const val PAY_NOW = "pay-now"
        const val DELETE_FOOD = "delete-food"
        const val GET_USER_MEAL = "get_user_meal_type_by_food"
        const val BUY_NOW_PROGRAM = "buyNow-program"
        const val MEMBERSHIP_PLAN = "membership-plan"
        const val GET_STUDIO_DETAILS = "studio-detail"
        const val WORKOUT_DETAIL_BY = "workout-detail-by-id"
        const val UPCOMING_APPOINTMENT = "list-client-appointment"
        const val CANCEL_APPOINTMENT = "user-cancel-appointment"
        const val WORKOUT_FEEDBACK = "workout-feedback"
        const val COACH_LIST = "coach-list"
        const val DEACTIVATE_ACCOUNT = "deactivate-account"
        const val CHAT_LIST = "chat-list-in-user"
        const val LAST_MESSAGE = "chat_between_user_and_coach"
        const val GET_WORKOUT_BY_FITNESS = "get-workout-by-fitness"
        const val COACH_BY_TYPE = "list-category"
        const val COACH_LISTING = "coach-list-by-category"
        const val COACH_PLANS = "coach-plans"
        const val COACH_FILTER = "coach-list-by-filter"
        const val CALL_BACK = "callback-request-by-client"
        const val PLANS_BREAKUP = "get-selected-plan-breakup"
        const val GRADE_SPECIAL = "get-specialization-and-slab"
        const val USER_SELECT = "user-selected-plan"

        const val SESSION_COMPLETE = "session-complete"


        const val DELETE_ACCOUNT = "delete-user-account"
        const val ACTIVATE_ACCOUNT_EMAIL = "active-account-with-email"
        const val ACTIVATE_ACCOUNT_NUMBER = "active-account-with-mobile"
        const val NOTIFICATION_LIST = "list-notifications"
        const val READ_NOTIFICATION = "read-notifications"
        const val FCM_TOKEN = "fcm-token"
        const val DOWNLOAD_PDF = "get-download-meal-plan"
        const val WATCH_SYNC = "sync-watch-health-data"
        const val STORE_CLIENT_QUICKBLOX_ID = "store-client-quickBloxId"


    }

}